/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * What a React catalog entry is, and what its rendering entry points receive.
 *
 * These types refer to each other: an implementation's `view` takes
 * `NodeViewProps`, which names a node holding an entry of the same catalog.
 * Keeping them together lets `adapter.tsx` build implementations and
 * `to_web_component.tsx` wrap them without importing each other.
 */

import type React from 'react';
import type {ZodTypeAny} from 'zod';
import type {ComponentApi, ComponentContext, ComponentNode} from '@a2ui/web_core/v0_9';
import type {WebComponentImplementation} from '@a2ui/web_core/v0_9/universal';

/** Renders a resolved child node, or falls back for an unresolved id. */
export type NodeBuildChild = (
  child: ComponentNode<ReactCatalogComponent> | string,
  basePath?: string,
) => React.ReactNode;

/** What a component implementation's `view` receives from the node surface. */
export type NodeViewProps = {
  node: ComponentNode<ReactCatalogComponent>;
  buildChild: NodeBuildChild;
};

/** A catalog entry implemented as a React component. */
export interface ReactComponentImplementation<
  Schema extends ZodTypeAny = ZodTypeAny,
> extends ComponentApi<Schema> {
  /**
   * The Custom Element that wraps this implementation, so it stays renderable
   * when its parent is a Web Component and resolves children through the DOM.
   * The factories in `adapter.tsx` register it and fill this in.
   */
  tagName?: string;
  /** The framework-specific rendering wrapper. */
  render: React.FC<{
    context: ComponentContext;
    buildChild: (id: string, basePath?: string) => React.ReactNode;
  }>;
  /**
   * Renders this component from a resolved `ComponentNode`. Generated by the
   * factories in `adapter.tsx`. When absent, `NodeView` renders through
   * `render`, handing it a `buildChild` that resolves ids through the node
   * layer.
   */
  view?: React.FC<NodeViewProps>;
}

/** Any entry a React catalog can hold: a React component or a Web Component. */
export type ReactCatalogComponent<Schema extends ZodTypeAny = ZodTypeAny> =
  | ReactComponentImplementation<Schema>
  | WebComponentImplementation<Schema>;

/** What the generic binder hands a presentational React component. */
export type ReactA2uiComponentProps<T> = {
  props: T;
  buildChild: (id: string, basePath?: string) => React.ReactNode;
  context: ComponentContext;
};
